---
- hosts: 172.31.19.113
  become: yes
  tasks:
  - include_tasks: myfile.yml

  - name: i want to copy file from ansible master to nodes
    copy:
       src: mystatic
       dest: /home/ubuntu/mystaticmystaticfile

  - name: i want to install webserver
    apt:
      name: apache2
      state: present

  - name: copy dynamic file into note site
    template:
      src: myindexfile.j2
      dest: /var/www/html/index.html